#!/bin/bash

DockerQtVersion=$1
DockerAppEnvi=$2
DockerAppName=$3
DockerAppParam=$4
DockerAppMaxCore="0,1,2,3,4,5,6,7,8,9,10,11"
DockerQtLibs=/usr/local/appversion/qtlibs/$DockerQtVersion
DockerAppVersion=$(cat /usr/local/appversion/release/$DockerAppEnvi/$DockerAppName/lastversion.txt)
DockerAppDir=/usr/local/appversion/release/$DockerAppEnvi/$DockerAppName
DockerAppLibs=$DockerAppDir/$DockerAppVersion
DockerAppSh=$DockerAppLibs/app.sh
DockerName="$DockerAppName"_"$DockerAppParam"
DockerAppConfigRun=$DockerAppDir/"$DockerAppParam".ini

rm -rf $DockerAppLibs/*.ini;
rm -rf $DockerAppSh;


echo -e "#!/bin/bash" > $DockerAppSh
echo -e "sudo unlink /etc/localtime;" >> $DockerAppSh
echo -e "sudo ln -s /usr/share/zoneinfo/Etc/GMT+2 /etc/localtime;" >> $DockerAppSh
echo -e "sudo apt-get install htop;" >> $DockerAppSh
echo -e "export LD_LIBRARY_PATH=/home/user/qtlibs:/home/user/app;" >> $DockerAppSh
echo -e "export QT_PLUGIN_PATH=/home/user/qtlibs/plugins" >> $DockerAppSh
echo -e "./app \$DockerAppParam" >> $DockerAppSh
chmod +x $DockerAppSh;

find $DockerAppDir -maxdepth 1 -mindepth 1 -iname '*.ini' -exec cp {} $DockerAppLibs \;

export existCheck=$(docker ps -a | grep $DockerName)
if [[ $existCheck == *"$DockerName"* ]]; then
	echo "parando docker";
	#export runVar=$(docker system prune /y);
	export runVar=$(docker stop $DockerName);
	export runVar=$(docker rm $DockerName);
	echo "docker removido";
fi

cat $DockerAppConfigRun

if [ -f $DockerAppConfigRun ]
then
	export DockerAppMaxCore=$(cat $DockerAppConfigRun);
fi

echo "docker starting";
echo "docker CPU : " $DockerAppMaxCore
export runVar=$(docker run -tid --restart unless-stopped --cap-add=sys_nice --cpuset-cpus=$DockerAppMaxCore -e "DockerAppParam=$DockerAppParam" -e "TZ=America/Fortaleza" -v $DockerQtLibs:/home/user/qtlibs -v $DockerAppLibs:/home/user/app --name="$DockerName" docker_qt bash dockerRun.sh);
echo "docker started";