apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8sAppName}
spec:
  selector:
    matchLabels:
      app: ${K8sAppName}
  replicas: ${NumReplicas}
  template:
    metadata:
      labels:
        app: ${K8sAppName}
    spec:
      containers:
        - name: ${K8sAppName}-container
          image: ${DockerImage}
          args:
          - /bin/sh
          - -c
          - touch /tmp/healthy; sleep 30;
          #  rm -rf /tmp/healthy; sleep 600
          command: [ "/bin/bash", "-ce", "sh /home/user/k8sRun.sh" ]
          volumeMounts:
            - mountPath: /tmp/.X11-unix
              name: x11-volume
            - mountPath: /home/user/qtlibs
              name: qt-libs
#            - mountPath: /home/user/app
#              name: qt-app
          resources:
            limits:
              cpu: ${DockerAppMaxCore}
              memory: ${DockerAppMaxMemory}
          env:
            - name: DISPLAY
            - name: QT_QPA_PLATFORM
              value: minimal
            - name: XDG_RUNTIME_DIR
              value: /tmp/runtime-developer
            - name: DockerAppParam
              value: ${DockerAppParam}
            - name: LD_LIBRARY_PATH
              value: /home/user/qtlibs/oracle:/home/user/qtlibs:/home/user/qtlibs/plugins:/home/user/qtlibs/plugins/sqldrivers:/home/user/app
          imagePullPolicy: Always
          ports:
            - containerPort: ${DockerAppPort}
#          readinessProbe:
#            exec:
#              command:
#              - cat
#              - /tmp/healthy
#            initialDelaySeconds: 60
#            periodSeconds: 5
      terminationGracePeriodSeconds: 60
      nodeSelector:
        #kubernetes.io/hostname: ${Node}
        general: "true"
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: x11-volume
          hostPath:
             #directory location on host
            path: /tmp/.X11-unix
            #this field is optional
            #type: Directory
        - name: qt-libs
          hostPath:
             #directory location on host
            path: ${DockerQtLibs}
             #this field is optional
            #type: Directory
#        - name: qt-app
#          hostPath:
#             #directory location on host
#            path: ${DockerAppLibs}
#             #this field is optional
#            #type: Directory

