apiVersion: v1
kind: Service
metadata:
  name: ${DockerAppName}-service
spec:
  type: NodePort
  ports:
    - port: ${DockerAppPort}
      nodePort: ${DockerAppHostPort}
  selector:
    app: ${DockerAppName}
