#!/bin/bash

export BINARYSERVER=$1
export BINARYSERVERUSER=$2
export BINARYBuildDir=/usr/local/appjavaversion

export FILENAME=./k8sDirsJavaPrepare.sh
scp $FILENAME $BINARYSERVERUSER@$BINARYSERVER:$BINARYBuildDir/$FILENAME;

export FILENAME=./k8sDeployJava
scp $FILENAME $BINARYSERVERUSER@$BINARYSERVER:$BINARYBuildDir/$FILENAME;

export FILENAME=./deployjava.sh
scp $FILENAME $BINARYSERVERUSER@$BINARYSERVER:$BINARYBuildDir/$FILENAME;

export FILENAME=./k8sPrepareTemplateJava.sh
scp $FILENAME $BINARYSERVERUSER@$BINARYSERVER:$BINARYBuildDir/$FILENAME;

export FILENAME=./k8sTemplateJava.yaml
scp $FILENAME $BINARYSERVERUSER@$BINARYSERVER:$BINARYBuildDir/$FILENAME;

export FILENAME=./k8sTemplateJavaService.yaml
scp $FILENAME $BINARYSERVERUSER@$BINARYSERVER:$BINARYBuildDir/$FILENAME;

export FILENAME=./app.conf
scp $FILENAME $BINARYSERVERUSER@$BINARYSERVER:$BINARYBuildDir/$FILENAME;