apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${AppName}
spec:
  selector:
    matchLabels:
      app: ${AppName}
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ${AppName}
    spec:
      containers:
        - name: ${AppName}-container
          image: ${DockerImage}
          resources:
            limits:
              cpu: ${DockerAppMaxCore}
          env:
            - name: CONFIGSERVER_URI
              value: ${CONFIGSERVER_URI}
            - name: ENCRYPT_KEY
              value: ${ENCRYPT_KEY}
            - name: EUREKASERVER_URI
              value: ${EUREKASERVER_URI}
            - name: HOSTNAME
              value: ${HOST_NAME}
            - name: PROFILE
              value: ${PROFILE}
            - name: SERVER_PORT
              value: '${SERVER_PORT}'
          imagePullPolicy: Always
          ports:
            - containerPort: ${DockerAppPort}
          readinessProbe:
            httpGet:
              path: ${URL_TESTE}
              port: ${DockerAppPort}
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
      terminationGracePeriodSeconds: 140
      nodeSelector:
        kubernetes.io/hostname: k8s-node-97
      imagePullSecrets:
        - name: registrypullsecret