apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${AppName}
spec:
  selector:
    matchLabels:
      app: ${AppName}
  replicas: 2
  template:
    metadata:
      labels:
        app: ${AppName}
    spec:
      containers:
        - name: ${AppName}-container
          image: ${DockerImage}
          resources:
            limits:
              cpu: ${DockerAppMaxCore}
          env:
            - name: CONFIGSERVER_URI
              value: ${CONFIGSERVER_URI}
            - name: ENCRYPT_KEY
              value: ${ENCRYPT_KEY}
            - name: EUREKASERVER_URI
              value: ${EUREKASERVER_URI}
            - name: HOSTNAME
              value: ${HOST_NAME}
            - name: PROFILE
              value: ${PROFILE}
            - name: SERVER_PORT
              value: '${SERVER_PORT}'
          imagePullPolicy: Always
          ports:
            - containerPort: ${DockerAppPort}
      terminationGracePeriodSeconds: 130
      nodeSelector:
        kubernetes.io/hostname: k8s-node-97
      imagePullSecrets:
        - name: registrypullsecret

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: ${AppName}-service
#spec:
#  type: NodePort
#  ports:
#    - port: ${DockerAppPort}
#      nodePort: ${DockerAppHostPort}
#  selector:
#    app: ${AppName}